 
################

#   Target

################

 

PROGRAMS_spu          := simple_spu 

LIBRARY_embed          := lib_simple_spu.a 
 

################

#   Local Defines

################

 

 

################

#   buildutils/make.footer

###############
IMPORTS := -lm

ifdef CELL_TOP

            include $(CELL_TOP)/buildutils/make.footer

else

            include ../../../../buildutils/make.footer

endif
